# Generated by Django 4.0.2 on 2022-03-31 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_remove_map_project'),
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='mapapp.map'),
        ),
    ]
