# Generated by Django 4.0.2 on 2022-05-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0002_comment_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
    ]
